### ISSUE TITLE
Task with Html format fail when using foundation

### ISSUE THREAD

**Issue by kevynb** [mavdi/grunt-cucumberjs#45] opened 2015-12-02 16:41 UTC
Hello!

I'm using version 0.8.2 and I'm having an error when running cucumber tests with the html format output option.
The error is 
```
Fatal error: Unable to read "node_modules/grunt-cucumberjs/templates/foundation/piechart.js" file (Error code: ENOENT).
```

The file `piechart.js` seems to be present in the bootstrap template, but not in the foundation one.

The piechat should just be skipped when using foundation, instead of crashing the whole thing

Edit: It works fine if you use bootstrap

**Comment by gkushang** [comment] 2015-12-02 17:51
@kevynb yes, it was a bug. Thanks for reporting it. [Pie Charts](http://htmlpreview.github.io/?https://github.com/gkushang/grunt-cucumberjs/blob/report/report/cucumber_report.html) are only available for `bootstrap` theme. However, the issue is fixed in the release **v0.8.3**. Please pull the latest module.

**Closed by gkushang** 2015-12-02 17:51 UTC
